spring:
  application:
    name: movies-api
  data:
    mongodb:
      uri: mongodb://localhost:27017/moviesdb
  # ===============================
  # = Redis configurations
  # ===============================ß
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    pool:
      max-active: 5
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 3000
  main:
    allow-circular-references: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/company-services
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: movies-app
      principal-attribute: preferred_username

app:
  cors:
    allowed-origins: http://localhost:3000

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

springdoc:
  show-actuator: true
  swagger-ui:
    groups-order: DESC
    disable-swagger-default-url: true

logging:
  level:
    org.springframework.security: DEBUG